/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface PageDashboard {
    }
    interface PageLogin {
    }
    interface PageProject {
        "project_id": string;
    }
    interface PartAddProjectModal {
        "uid": string;
    }
    interface PartLoading {
    }
    interface PartProjectSnippet {
        "project_id": string;
        "projectname": string;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPageDashboardElement extends Components.PageDashboard, HTMLStencilElement {
    }
    var HTMLPageDashboardElement: {
        prototype: HTMLPageDashboardElement;
        new (): HTMLPageDashboardElement;
    };
    interface HTMLPageLoginElement extends Components.PageLogin, HTMLStencilElement {
    }
    var HTMLPageLoginElement: {
        prototype: HTMLPageLoginElement;
        new (): HTMLPageLoginElement;
    };
    interface HTMLPageProjectElement extends Components.PageProject, HTMLStencilElement {
    }
    var HTMLPageProjectElement: {
        prototype: HTMLPageProjectElement;
        new (): HTMLPageProjectElement;
    };
    interface HTMLPartAddProjectModalElement extends Components.PartAddProjectModal, HTMLStencilElement {
    }
    var HTMLPartAddProjectModalElement: {
        prototype: HTMLPartAddProjectModalElement;
        new (): HTMLPartAddProjectModalElement;
    };
    interface HTMLPartLoadingElement extends Components.PartLoading, HTMLStencilElement {
    }
    var HTMLPartLoadingElement: {
        prototype: HTMLPartLoadingElement;
        new (): HTMLPartLoadingElement;
    };
    interface HTMLPartProjectSnippetElement extends Components.PartProjectSnippet, HTMLStencilElement {
    }
    var HTMLPartProjectSnippetElement: {
        prototype: HTMLPartProjectSnippetElement;
        new (): HTMLPartProjectSnippetElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "page-dashboard": HTMLPageDashboardElement;
        "page-login": HTMLPageLoginElement;
        "page-project": HTMLPageProjectElement;
        "part-add-project-modal": HTMLPartAddProjectModalElement;
        "part-loading": HTMLPartLoadingElement;
        "part-project-snippet": HTMLPartProjectSnippetElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface PageDashboard {
    }
    interface PageLogin {
    }
    interface PageProject {
        "project_id"?: string;
    }
    interface PartAddProjectModal {
        "uid"?: string;
    }
    interface PartLoading {
    }
    interface PartProjectSnippet {
        "onBeginEditProject"?: (event: CustomEvent<any>) => void;
        "onFinishEditProject"?: (event: CustomEvent<any>) => void;
        "onProjectDeleted"?: (event: CustomEvent<any>) => void;
        "project_id"?: string;
        "projectname"?: string;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "page-dashboard": PageDashboard;
        "page-login": PageLogin;
        "page-project": PageProject;
        "part-add-project-modal": PartAddProjectModal;
        "part-loading": PartLoading;
        "part-project-snippet": PartProjectSnippet;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "page-dashboard": LocalJSX.PageDashboard & JSXBase.HTMLAttributes<HTMLPageDashboardElement>;
            "page-login": LocalJSX.PageLogin & JSXBase.HTMLAttributes<HTMLPageLoginElement>;
            "page-project": LocalJSX.PageProject & JSXBase.HTMLAttributes<HTMLPageProjectElement>;
            "part-add-project-modal": LocalJSX.PartAddProjectModal & JSXBase.HTMLAttributes<HTMLPartAddProjectModalElement>;
            "part-loading": LocalJSX.PartLoading & JSXBase.HTMLAttributes<HTMLPartLoadingElement>;
            "part-project-snippet": LocalJSX.PartProjectSnippet & JSXBase.HTMLAttributes<HTMLPartProjectSnippetElement>;
        }
    }
}
