/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppAddProjectModal {
        "user_id": string;
    }
    interface AppDashboard {
        "shouldload": number;
    }
    interface AppHome {
    }
    interface AppLoading {
    }
    interface AppLogin {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppProject {
        "project_id": string;
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppAddProjectModalElement extends Components.AppAddProjectModal, HTMLStencilElement {
    }
    var HTMLAppAddProjectModalElement: {
        prototype: HTMLAppAddProjectModalElement;
        new (): HTMLAppAddProjectModalElement;
    };
    interface HTMLAppDashboardElement extends Components.AppDashboard, HTMLStencilElement {
    }
    var HTMLAppDashboardElement: {
        prototype: HTMLAppDashboardElement;
        new (): HTMLAppDashboardElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppLoadingElement extends Components.AppLoading, HTMLStencilElement {
    }
    var HTMLAppLoadingElement: {
        prototype: HTMLAppLoadingElement;
        new (): HTMLAppLoadingElement;
    };
    interface HTMLAppLoginElement extends Components.AppLogin, HTMLStencilElement {
    }
    var HTMLAppLoginElement: {
        prototype: HTMLAppLoginElement;
        new (): HTMLAppLoginElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppProjectElement extends Components.AppProject, HTMLStencilElement {
    }
    var HTMLAppProjectElement: {
        prototype: HTMLAppProjectElement;
        new (): HTMLAppProjectElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-add-project-modal": HTMLAppAddProjectModalElement;
        "app-dashboard": HTMLAppDashboardElement;
        "app-home": HTMLAppHomeElement;
        "app-loading": HTMLAppLoadingElement;
        "app-login": HTMLAppLoginElement;
        "app-profile": HTMLAppProfileElement;
        "app-project": HTMLAppProjectElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppAddProjectModal {
        "onOnProjectSaved"?: (event: CustomEvent<any>) => void;
        "user_id"?: string;
    }
    interface AppDashboard {
        "shouldload"?: number;
    }
    interface AppHome {
    }
    interface AppLoading {
    }
    interface AppLogin {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppProject {
        "project_id"?: string;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-add-project-modal": AppAddProjectModal;
        "app-dashboard": AppDashboard;
        "app-home": AppHome;
        "app-loading": AppLoading;
        "app-login": AppLogin;
        "app-profile": AppProfile;
        "app-project": AppProject;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-add-project-modal": LocalJSX.AppAddProjectModal & JSXBase.HTMLAttributes<HTMLAppAddProjectModalElement>;
            "app-dashboard": LocalJSX.AppDashboard & JSXBase.HTMLAttributes<HTMLAppDashboardElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-loading": LocalJSX.AppLoading & JSXBase.HTMLAttributes<HTMLAppLoadingElement>;
            "app-login": LocalJSX.AppLogin & JSXBase.HTMLAttributes<HTMLAppLoginElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-project": LocalJSX.AppProject & JSXBase.HTMLAttributes<HTMLAppProjectElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
